# R packages
RPKG1: /home/koki/Software/R-3.6.0/library/TENxPBMCData/DESCRIPTION
RPKG2: /home/koki/Software/R-3.6.0/library/Seurat/DESCRIPTION
RPKG3: /home/koki/Software/R-3.6.0/library/tagcloud/DESCRIPTION
RPKG4: /home/koki/Software/R-3.6.0/library/RColorBrewer/DESCRIPTION
RPKG5: /home/koki/Software/R-3.6.0/library/scales/DESCRIPTION
RPKG6: /home/koki/Software/R-3.6.0/library/fields/DESCRIPTION
RPKG7: /home/koki/Software/R-3.6.0/library/rTensor/DESCRIPTION
RPKG8: /home/koki/Software/R-3.6.0/library/Rtsne/DESCRIPTION

